-- D&L ACC - تقييمات الموقع بعد الطلب. شغّله مرة واحدة في Supabase > SQL Editor.
CREATE TABLE IF NOT EXISTS public.site_reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name text NOT NULL DEFAULT 'عميل',
  rating int NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment text NOT NULL DEFAULT '',
  order_id bigint,
  approved boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.site_reviews ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "site_reviews insert" ON public.site_reviews;
CREATE POLICY "site_reviews insert" ON public.site_reviews FOR INSERT TO anon, authenticated WITH CHECK (approved = false);
DROP POLICY IF EXISTS "site_reviews read approved" ON public.site_reviews;
CREATE POLICY "site_reviews read approved" ON public.site_reviews FOR SELECT TO anon, authenticated USING (approved = true OR auth.role() = 'authenticated');
DROP POLICY IF EXISTS "site_reviews admin update" ON public.site_reviews;
CREATE POLICY "site_reviews admin update" ON public.site_reviews FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "site_reviews admin delete" ON public.site_reviews;
CREATE POLICY "site_reviews admin delete" ON public.site_reviews FOR DELETE TO authenticated USING (true);
